exports.seed = async function (knex) {
  await knex("comments").del();
  await knex("comments").insert([
    {
      commentid: 1,
      name: "User 1",
      comment: "This is a comment 1",
      likes: 10,
      memoryid: 1,
      timestamp: knex.fn.now(),
    },
    {
      commentid: 2,
      name: "User 2",
      comment: "This is a comment 2",
      likes: 20,
      memoryid: 1,
      timestamp: knex.fn.now(),
    },
    {
      commentid: 3,
      name: "User 3",
      comment: "This is a comment 3",
      likes: 30,
      memoryid: 2,
      timestamp: knex.fn.now(),
    },
    {
      commentid: 4,
      name: "User 4",
      comment: "This is a comment 4",
      likes: 40,
      memoryid: 2,
      timestamp: knex.fn.now(),
    },
    {
      commentid: 5,
      name: "User 5",
      comment: "This is a comment 5",
      likes: 50,
      memoryid: 3,
      timestamp: knex.fn.now(),
    },
    {
      commentid: 6,
      name: "User 6",
      comment: "This is a comment 6",
      likes: 60,
      memoryid: 3,
      timestamp: knex.fn.now(),
    },
    {
      commentid: 7,
      name: "User 7",
      comment: "This is a comment 7",
      likes: 70,
      memoryid: 4,
      timestamp: knex.fn.now(),
    },
    {
      commentid: 8,
      name: "User 8",
      comment: "This is a comment 8",
      likes: 80,
      memoryid: 4,
      timestamp: knex.fn.now(),
    },
    {
      commentid: 9,
      name: "User 9",
      comment: "This is a comment 9",
      likes: 90,
      memoryid: 5,
      timestamp: knex.fn.now(),
    },
    {
      commentid: 10,
      name: "User 10",
      comment: "This is a comment 10",
      likes: 100,
      memoryid: 5,
      timestamp: knex.fn.now(),
    },
  ]);
};
