exports.seed = async function (knex) {
  await knex("memories").del();
  await knex("memories").insert([
    {
      id: 1,
      title: "Cute Baby 1",
      description: "This is a cute baby smiling",
      image:
        "https://images.unsplash.com/photo-1650023932630-0c249bbf2e96?q=80&w=1943&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      likes: 10,
      user_id: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 2,
      title: "Cute Baby 2",
      description: "This is a cute baby laughing",
      image: "baby2.jpg",
      likes: 20,
      user_id: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 3,
      title: "Cute Baby 3",
      description: "This is a cute baby sleeping",
      image: "baby3.jpg",
      likes: 30,
      user_id: 2,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 4,
      title: "Cute Baby 4",
      description: "This is a cute baby playing",
      image: "baby4.jpg",
      likes: 40,
      user_id: 2,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 5,
      title: "Cute Baby 5",
      description: "This is a cute baby crawling",
      image: "baby5.jpg",
      likes: 50,
      user_id: 3,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 6,
      title: "Cute Baby 6",
      description: "This is a cute baby eating",
      image: "baby6.jpg",
      likes: 60,
      user_id: 3,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 7,
      title: "Cute Baby 7",
      description: "This is a cute baby dancing",
      image: "baby7.jpg",
      likes: 70,
      user_id: 4,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 8,
      title: "Cute Baby 8",
      description: "This is a cute baby singing",
      image: "baby8.jpg",
      likes: 80,
      user_id: 4,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 9,
      title: "Cute Baby 9",
      description: "This is a cute baby crying",
      image: "baby9.jpg",
      likes: 90,
      user_id: 5,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 10,
      title: "Cute Baby 10",
      description: "This is a cute baby waving",
      image: "baby10.jpg",
      likes: 100,
      user_id: 5,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
  ]);
};
